### ISSUE TITLE
Should `connect()` exist as a permission on its own?

### ISSUE THREAD

**Issue by gotlougit** [boustrophedon/extrasafe#23]
Currently, the `connect()` syscall, which is dangerous, is only allowed if we call `allow_start_tcp_clients()`. However, it seems like Unix sockets also break if this isn't allowed. 

I propose we create a separate method that just allows `connect()` and returns a `YesReally<Networking>` in order to denote its danger to the application developer, but I'd like to learn more about this design choice and any drawbacks it may have.

**Comment by boustrophedon** [comment]
I'll try to take a look at this tomorrow - it sounds like a reasonable idea.
