### ISSUE TITLE
Panic on unsupported OS

### ISSUE THREAD

**Issue by TedDriggs** [boustrophedon/extrasafe#3]
The `ExtraSafeError::UnsupportedOSError` variant exists as defense-in-depth against `seccomp` unexpectedly building on Linux.

This feels odd for two reasons:

1.  The crate can avoid giving the caller a `SafetyContext` altogether on an incompatible OS, so the check is needlessly delayed.
2. This is borderline a code error, not an unforeseen runtime condition. Following Rust's panic-vs-error philosophy (explained in great detail by Joe Duffy [here](http://joeduffyblog.com/2016/02/07/the-error-model/)), this could be reason to panic.

# Proposal
Move the OS check to `SafetyContext::new`. Then _either_ make `SafetyContext::new` return `Result<Self, UnsupportedOsError>` _or_ have `new` panic and add a second function, `SafetyContext::try_new` for authors who are writing OS-agnostic code.

**Comment by boustrophedon** [comment]
I've been thinking about how to do multi-platform support and I think the idea that I'm going to go with will mitigate this issue by just not compiling if the OS isn't supported.

I'm going to close this but thank you for giving this some thought!
