### ISSUE TITLE
Add Default impl for SafetyContext (or document why it's not available)

### ISSUE THREAD

**Issue by TedDriggs** [boustrophedon/extrasafe#4]
Looking at `SafetyContext`, is [`clippy::new_without_default`](https://rust-lang.github.io/rust-clippy/master/#new_without_default) being suppressed because `SafetyContext::default` won't be `#[must_use]`?

Since `impl Default` is common enough to merit a clippy lint when it's omitted, I think it would be helpful to document why this struct chooses to eschew it.

**Comment by boustrophedon** [comment]
I simply don't want there to be a "SafetyContext::default" because it could be misleading - what would the "default context" be, would it include some rulesets by default? I'm not sure how you would document it (just a comment above the clippy lint?) but if you'd like to I'd be glad to accept a PR for it.

**Comment by TedDriggs** [comment]
It would be the same as calling `SafetyContext::new()`

**Comment by boustrophedon** [comment]
Sure, I understand that, but then why do you want it?

**Comment by TedDriggs** [comment]
Tons of the Rust ecosystem has code that is generic over `T: Default`. It’s the same reason why structs impl Debug instead of exposing an inherent method that writes the contents to stderr.

**Comment by boustrophedon** [comment]
I'm not trying to be a jerk here but I really don't see a case where you would want this behavior specifically in the context of extrasafe. Can you please provide a specific use-case?

**Comment by boustrophedon** [comment]
I'm going to close this for now but if someone comes up with a use-case feel free to comment!
