### ISSUE TITLE
Documentation suggestion: applicability for subprocesses

### ISSUE THREAD

**Issue by emarsden** [boustrophedon/extrasafe#40]
Thanks for this library.

I'm not familiar with the details of the different security APIs used by extrasafe. I believe (but am not certain) that they apply to forked subprocesses, which seems like it might be useful when running ffmpeg for instance. The documentation refers to "your code"; it might be useful to mention applicability for forked processes more explicitly.

**Comment by boustrophedon** [comment]
Hi! That's a good point. Seccomp, landlock, and namespaces all apply to forked threads and processes - that should probably be mentioned somewhere at the top of the user guide or in the readme.

**Comment by boustrophedon** [comment]
I added an update in the user guide and added a second link to the user guide at the top of the readme!
