### ISSUE TITLE
Is this intended to be a Linux-only crate or does it have ambitions for other OSs, too?

### ISSUE THREAD

**Issue by heinrich5991** [boustrophedon/extrasafe#56]
E.g. via the [`pledge`](https://man.openbsd.org/pledge.2)/[`unveil`](https://man.openbsd.org/unveil.2) API of OpenBSD.

**Comment by boustrophedon** [comment]
Originally I was considering making it cross-platform but in its current state it uses a lot of Linux-specific APIs like user namespaces, capabilities, Landlock, and (coming soon™ for the past six months) cgroups.

There are some other projects that attempt to be more generic across multiple OSes like [phylum-dev/birdcage](https://github.com/phylum-dev/birdcage) and I believe the [cosmopolitan project](https://github.com/jart/cosmopolitan) also has some cross-platform security feature support.

**Comment by heinrich5991** [comment]
I see, thanks for the quick answer. :)
