### ISSUE TITLE
SeccompError, basic example not working

### ISSUE THREAD

**Issue by codekeyz** [boustrophedon/extrasafe#57]
```rust
 extrasafe::SafetyContext::new()
        .enable(
            extrasafe::builtins::SystemIO::nothing()
                .allow_stdin()
                .allow_stderr(), // .allow_create_in_dir(&mount_point)
                                 // .allow_read_path(&mount_point),
        )
        .unwrap()
        .apply_to_current_thread()
        .unwrap();
```

This is failing with the error below. Not sure what's wrong
```
called `Result::unwrap()` on an `Err` value: SeccompError(Seccomp(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
```

**Comment by boustrophedon** [comment]
You caught me just as I went on vacation and don't have easy access to a linux machine.

I'm assuming that the commented allow_create_in_dir and allow_read_path are not part of the issue.

What kind of environment are you running the code in? The manpage for seccomp (https://man7.org/linux/man-pages/man2/seccomp.2.html) lists several different errors for EINVAL, including "A secure computing mode has already been set" and "operation is unknown or is not supported by this kernel version or configuration". For example, if your program already has enabled seccomp or (maybe?) has called prctl(PR_SET_NO_NEW_PRIVS), or if somehow your kernel was compiled without seccomp support. Also, if you're using WSL I'm not sure if it supports seccomp.

On Wed, Dec 4, 2024, at 5:52 AM, Chima Precious wrote:
> 
> 
>  extrasafe::SafetyContext::new()
>         .enable(
>             extrasafe::builtins::SystemIO::nothing()
>                 .allow_stdin()
>                 .allow_stderr(), // .allow_create_in_dir(&mount_point)
>                                  // .allow_read_path(&mount_point),
>         )
>         .unwrap()
>         .apply_to_current_thread()
>         .unwrap();
> This is failing with the error below. Not sure what's wrong
> 
> `called `Result::unwrap()` on an `Err` value: SeccompError(Seccomp(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::result::unwrap_failed
>    3: core::result::Result<T,E>::unwrap
`
